# Generated by Django 5.0.4 on 2024-04-15 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='item_date',
            field=models.DateField(default='2002/02/28'),
        ),
        migrations.AddField(
            model_name='item',
            name='item_quantity',
            field=models.IntegerField(default=0),
        ),
    ]
