# Generated by Django 5.0.4 on 2024-04-15 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0002_item_item_date_item_item_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='item_date',
            field=models.DateField(default='2002-02-28'),
        ),
    ]
